# Generated by Django 3.0.13 on 2021-06-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='dob',
        ),
    ]
