# Generated by Django 3.0.13 on 2021-06-14 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_instructor_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
