# Generated by Django 3.0.13 on 2021-09-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseContentStat',
        ),
    ]
