# Generated by Django 3.0.13 on 2021-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
