# Generated by Django 3.0.13 on 2021-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.ImageField(default='certificate.jpg', upload_to='certificate'),
        ),
    ]
