# Generated by Django 3.0.13 on 2021-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210919_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.ImageField(default='certificates.jpg', upload_to='certificates'),
        ),
    ]
