# Generated by Django 3.0.13 on 2021-09-20 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210920_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatus',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
