# Generated by Django 3.0.13 on 2021-09-25 09:05

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursestatus_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='code',
            field=models.IntegerField(default=courses.models.random_code),
        ),
    ]
