# Generated by Django 3.0.13 on 2021-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_certificate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='code',
            field=models.IntegerField(),
        ),
    ]
